import json
from datetime import datetime
from jinja2 import Template
from weasyprint import HTML
from pathlib import Path

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Pentest Report - {{ target }}</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 900px; margin: 0 auto; padding: 20px; background-color: #f4f4f9; }
        .header { background: #800000; color: #fff; padding: 30px; text-align: center; border-radius: 8px 8px 0 0; }
        .section { background: #fff; padding: 20px; margin-top: 20px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
        h1, h2, h3 { color: #800000; }
        .finding { border-left: 5px solid #800000; padding: 10px 20px; margin-bottom: 10px; background: #fff5f5; }
        .severity-critical { color: #ff0000; font-weight: bold; }
        .severity-high { color: #ff4500; font-weight: bold; }
        .severity-medium { color: #ffa500; font-weight: bold; }
        .severity-low { color: #2e8b57; font-weight: bold; }
        .evidence { background: #2d2d2d; color: #f8f8f2; padding: 15px; border-radius: 5px; font-family: monospace; overflow-x: auto; font-size: 12px; }
        .footer { text-align: center; margin-top: 50px; font-size: 0.8em; color: #777; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { text-align: left; padding: 12px; border-bottom: 1px solid #ddd; }
        th { background-color: #f2f2f2; }
    </style>
</head>
<body>
    <div class="header">
        <h1>AI PENTEST REPORT</h1>
        <p>Target: {{ target }}</p>
        <p>Date: {{ timestamp }}</p>
    </div>

    <div class="section">
        <h2>Executive Summary</h2>
        <p>This automated security assessment was performed by the <strong>AI AGENT CHAINS CAPILOT</strong> workflow engine. The scan analyzed the target <strong>{{ target }}</strong> using a deterministic 6-phase security pipeline.</p>
        <p><strong>Overall Status:</strong> {{ status }}</p>
        <p><strong>Findings Summary:</strong> Found {{ findings|length }} security findings/vulnerabilities.</p>
    </div>

    <div class="section">
        <h2>Scope & Infrastructure</h2>
        <table>
            <tr><th>Target</th><td>{{ target }}</td></tr>
            <tr><th>Scope</th><td>{{ scope }}</td></tr>
            <tr><th>Mode</th><td>{{ "Deep" if deep else "Standard" }}</td></tr>
            <tr><th>AI Provider</th><td>{{ model_provider }}</td></tr>
        </table>
    </div>

    <div class="section">
        <h2>Security Findings</h2>
        {% if findings %}
            {% for finding in findings %}
                <div class="finding">
                    <h3>{{ finding.value }}</h3>
                    <p><strong>Type:</strong> {{ finding.type }} | <strong>Severity:</strong> <span class="severity-{{ finding.severity|lower }}">{{ finding.severity|upper }}</span></p>
                    <p><strong>Evidence:</strong> {{ finding.evidence }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p>No significant vulnerabilities were identified during this assessment.</p>
        {% endif %}
    </div>

    <div class="section">
        <h2>Raw Evidence Log</h2>
        {% for item in evidence %}
            <h3>Tool: {{ item.tool|upper }}</h3>
            <div class="evidence">
                <pre>{{ item.data | tojson(indent=2) }}</pre>
            </div>
        {% endfor %}
    </div>

    <div class="footer">
        <p>Generated by AI Pentest Agent - Deterministic Security Workflow Engine</p>
        <p>&copy; 2024 AI Pentest Agent</p>
    </div>
</body>
</html>
"""

def generate_report(state: dict, format: str = "html") -> bytes:
    """Generate a report in HTML or PDF format."""
    template = Template(HTML_TEMPLATE)

    # Pre-processing state data for the template
    data = {
        "target": state.get("target"),
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "status": state.get("status", "Unknown"),
        "findings": state.get("findings", []),
        "evidence": state.get("evidence", []),
        "scope": state.get("scope", "N/A"),
        "deep": state.get("deep", False),
        "model_provider": state.get("model_provider", "google")
    }

    html_content = template.render(**data)

    if format == "pdf":
        return HTML(string=html_content).write_pdf()

    return html_content.encode("utf-8")
